allow-branch = ["master"]
consolidate-commits = true
consolidate-pushes = true
shared-version = true
sign-commit = true
sign-tag = true

[[pre-release-replacements]]
file = "Changes.md"
search = "<!-- next-header -->"
replace = "<!-- next-header -->\n\n## {{Unreleased}} - {{ReleaseDate}}\n"
exactly = 1

[[pre-release-replacements]]
file = "Changes.md"
search = "{{Unreleased}}"
replace = "{{version}}"

[[pre-release-replacements]]
file = "Changes.md"
search = "{{ReleaseDate}}"
replace = "{{date}}"
