# See examples/bin/install-dev-tools.sh for an example script to install all
# of the tools needed by this config. You can copy it into your project and
# modify it as needed to only install the tools you need.
[commands.golangci-lint]
type = "lint"
include = "**/*.go"
run_mode = "root"
chdir = true
cmd = [
    "golangci-lint",
    "run",
    "-c",
    "$PRECIOUS_ROOT/golangci-lint.yml",
]
env = { "FAIL_ON_WARNINGS" = "1" }
ok_exit_codes = [0]
lint_failure_exit_codes = [1]

[commands.goimports]
type = "tidy"
include = "**/*.go"
cmd = ["goimports", "-w"]
ok_exit_codes = [0]

# See check-go-mod.sh in helpers dir
[commands.check-go-mod]
type = "lint"
include = "**/*.go"
run_mode = "dirs"
chdir = true
cmd = ["$PRECIOUS_ROOT/dev/bin/check-go-mod.sh"]
expect_stderr = true
ok_exit_codes = [0]
lint_failure_exit_codes = [1]

[commands.omegasort-gitignore]
type = "both"
include = "**/.gitignore"
cmd = [ "omegasort", "--sort=path" ]
lint_flags = "--check"
tidy_flags = "--in-place"
ok_exit_codes = 0
lint_failure_exit_codes = 1
expect_stderr = true
