# See examples/bin/install-dev-tools.sh for an example script to install all
# of the tools needed by this config. You can copy it into your project and
# modify it as needed to only install the tools you need.
exclude = [
  "target",
]

[commands.rustfmt]
type    = "both"
include = "**/*.rs"
cmd     = "rustfmt"
lint_flags = "--check"
ok_exit_codes = 0
lint_failure_exit_codes = 1

[commands.clippy]
type     = "lint"
include  = "**/*.rs"
run_mode = "root"
chdir    = true
# See the helpers dir for this script. You have to edit it for your project.
cmd      = "$PRECIOUS_ROOT/helpers/force-clippy.sh"
ok_exit_codes = 0
lint_failure_exit_codes = 101
expect_stderr = true

[commands.omegasort-gitignore]
type = "both"
include = "**/.gitignore"
cmd = [ "omegasort", "--sort=path" ]
lint_flags = "--check"
tidy_flags = "--in-place"
ok_exit_codes = 0
lint_failure_exit_codes = 1
expect_stderr = true
