name: Tests and release

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "precious-*"
  pull_request:

env:
  CRATE_NAME: precious
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1

jobs:
  test:
    name: ${{ matrix.platform.os-name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          # Platforms that don't work:
          #
          # - sparc64-unknown-linux-gnu - cannot compile openssl-sys
          # - x86_64-unknown-illumos - weird error compiling openssl - "bin/sh: 1: granlib: not found"

          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-freebsd
            bin: precious
            name: precious-FreeBSD-x86_64.tar.gz
            skip_tests: true
          - os-name: Linux-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: precious
            name: precious-Linux-x86_64-musl.tar.gz
          - os-name: Linux-aarch64
            runs-on: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            bin: precious
            name: precious-Linux-aarch64-musl.tar.gz
          - os-name: Linux-arm
            runs-on: ubuntu-20.04
            target: arm-unknown-linux-musleabi
            bin: precious
            name: precious-Linux-arm-musl.tar.gz
          - os-name: Linux-i686
            runs-on: ubuntu-20.04
            target: i686-unknown-linux-musl
            bin: precious
            name: precious-Linux-i686-musl.tar.gz
            skip_tests: true
          - os-name: Linux-powerpc
            runs-on: ubuntu-20.04
            target: powerpc-unknown-linux-gnu
            bin: precious
            name: precious-Linux-powerpc-gnu.tar.gz
            skip_tests: true
          - os-name: Linux-powerpc64
            runs-on: ubuntu-20.04
            target: powerpc64-unknown-linux-gnu
            bin: precious
            name: precious-Linux-powerpc64-gnu.tar.gz
            skip_tests: true
          - os-name: Linux-powerpc64le
            runs-on: ubuntu-20.04
            target: powerpc64le-unknown-linux-gnu
            bin: precious
            name: precious-Linux-powerpc64le.tar.gz
            skip_tests: true
          - os-name: Linux-riscv64
            runs-on: ubuntu-20.04
            target: riscv64gc-unknown-linux-gnu
            bin: precious
            name: precious-Linux-riscv64gc-gnu.tar.gz
          - os-name: Linux-s390x
            runs-on: ubuntu-20.04
            target: s390x-unknown-linux-gnu
            bin: precious
            name: precious-Linux-s390x-gnu.tar.gz
            skip_tests: true
          - os-name: NetBSD-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-netbsd
            bin: precious
            name: precious-NetBSD-x86_64.tar.gz
            skip_tests: true
          - os-name: Windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
            bin: precious.exe
            name: precious-Windows-aarch64.zip
            skip_tests: true
          - os-name: Windows-i686
            runs-on: windows-latest
            target: i686-pc-windows-msvc
            bin: precious.exe
            name: precious-Windows-i686.zip
            skip_tests: true
          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            bin: precious.exe
            name: precious-Windows-x86_64.zip
          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
            bin: precious
            name: precious-Darwin-x86_64.tar.gz
          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
            bin: precious
            name: precious-Darwin-aarch64.tar.gz
        toolchain:
          - stable
        include:
          - platform:
              os-name: Linux-x86_64
              runs-on: ubuntu-20.04
              target: x86_64-unknown-linux-musl
              bin: precious
            toolchain: beta
          - platform:
              os-name: Linux-x86_64
              runs-on: ubuntu-20.04
              target: x86_64-unknown-linux-musl
              bin: precious
            toolchain: nightly
    steps:
      - uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: true
          # This works around the issue in https://github.com/cross-rs/cross/issues/1450. The `main`
          # branch updated its images long ago, but the last cross release, 0.2.5, is still using
          # Ubuntu 16.04 as the base for some images.
          cross-version: 4090beca3cfffa44371a5bba524de3a578aa46c3
      - name: Run tests
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "test"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
        if: ${{ !matrix.platform.skip_tests }}
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: precious
          target: ${{ matrix.platform.target }}
        if: matrix.toolchain == 'stable'
