name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "precious-*"
  pull_request:

env:
  CRATE_NAME: precious
  RUST_BACKTRACE: 1

# There's not much value in running self-check on multiple platforms. Either
# we're lint-clean or not. We do run on each rust target to catch warnings
# coming from clippy in future rust versions.
jobs:
  lint:
    name: Lint self
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy,rustfmt
      - name: Run cargo install
        run: cargo install --path . --locked
      - name: Install mise
        run: |
          set -e
          set -x
          curl https://mise.run | sh
          mise install
      - name: "Run precious lint --all"
        run: mise exec -- $HOME/.cargo/bin/precious --debug lint --all
